name: CD - Deploy to Railway

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Build application
      run: mvn clean package -DskipTests
      
    - name: Deploy to Railway
      uses: railwayapp/railway-deploy@v1
      with:
        railway-token: ${{ secrets.RAILWAY_TOKEN }}
        service: one-click-video-generator
        detach: true
        
    - name: Health check
      run: |
        echo "Waiting for deployment to be ready..."
        sleep 30
        curl -f ${{ secrets.RAILWAY_URL }}/health || exit 1
        
    - name: Notify deployment success
      if: success()
      run: |
        echo "🚴‍♂️ Riding Roney Video Generator deployed successfully!"
        echo "URL: ${{ secrets.RAILWAY_URL }}"
        
    - name: Notify deployment failure
      if: failure()
      run: |
        echo "❌ Deployment failed!"
        exit 1
